name: arbify
description: >
  A package providing support for internationalizing
  Flutter applications using intl package with Arbify.
version: 0.0.0
homepage: https://github.com/Arbify/arbify_flutter

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  args: ^1.6.0
  dio: ^3.0.9
  intl_translation: ^0.17.10
  mockito: ^4.1.1
  path: ^1.6.4
  pedantic: ^1.0.0
  petitparser: ^3.0.4
  yaml: ^2.2.1

executables:
  - download
